// Login
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';


// Article
export const CREATE_ARTICLE_REQUEST = 'CREATE_ARTICLE_REQUEST';
export const CREATE_ARTICLE_FAILURE = 'CREATE_ARTICLE_FAILURE';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_DUPLICATE = 'CREATE_ARTICLE_DUPLICATE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_ARTICLE = 'DESTROY_ARTICLE';
export const TITLE_TYPING = 'TITLE_TYPING';
export const CONTENT_INPUT_TYPING = 'CONTENT_INPUT_TYPING';
export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';
export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST';
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE';

// tag
export const ARTICLE_TAG_ADDITION = 'ARTICLE_TAG_ADDITION';
export const ARTICLE_TAG_DELETE   = 'ARTICLE_TAG_DELETE';
export const ARTICLE_TAG_DRAG     = 'ARTICLE_TAG_DRAG';
export const CREATE_ARTICLE_TAG_REQUEST = "CREATE_ARTICLE_TAG_REQUEST";
export const CREATE_ARTICLE_TAG_FAILURE = "CREATE_ARTICLE_TAG_FAILURE";
export const CLEAR_NEW_ARTICLE_TAGS = "CLEAR_NEW_ARTICLE_TAGS"

// ArticleMeta
export const GET_ARTICLE_META_REQUEST = 'GET_ARTICLE_META_REQUEST';
export const GET_ARTICLE_META_FAILURE = 'GET_ARTICLE_META_FAILURE';
export const CREATE_ARTICLE_META_REQUEST = 'CREATE_ARTICLE_META_REQUEST';
export const CREATE_ARTICLE_META_FAILURE = 'CREATE_ARTICLE_META_FAILURE';
export const UPDATE_ARTICLE_META_REQUEST = 'UPDATE_ARTICLE_META_REQUEST';
export const UPDATE_ARTICLE_META_FAILURE = 'UPDATE_ARTICLE_META_FAILURE';

// comments
export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';
